"""Layer 1 — latent strength: separating driver skill from constructor advantage.

A Bayesian rank-ordered logit (Plackett-Luce) over race finishing orders, fitted
jointly across 2025 and 2026 with the regulation boundary built into the prior
structure rather than handled by dropping data.

The central idea
----------------
A finishing order is generated by repeatedly picking the best remaining car:

    P(order) = prod_k  exp(theta_(k)) / sum_{j >= k} exp(theta_(j))

with `theta = driver skill + constructor strength`. Fitting that over many races
recovers both terms — but only because of the constraints below.

Three modelling decisions, each forced by the data rather than chosen for taste
-------------------------------------------------------------------------------

1. **Driver skill spans the regulation change; constructor strength does not.**
   2026 reset the power units, aerodynamics and car dimensions, so a team's 2025
   pace says nothing about its 2026 pace. Skill, being a property of the human,
   carries. So `skill` is one parameter per driver across both seasons, while the
   constructor terms are severed at the boundary: `car_2025` and `car_2026` are
   independent draws. Drivers who changed teams over the winter are what tie the
   two eras together — without them the 2026 constructor scale would float free.

2. **Driver skill may step at the regulation boundary; 2026 constructor strength
   follows a random walk.** Each driver has a 2025 level plus a partially-pooled
   2026 delta, so the older season acts as a *prior* on current skill rather than
   as equally-weighted evidence. This is not decoration: forcing skill to be
   constant across both seasons put Antonelli — six wins and the championship lead
   in 2026 — seventh in the forecast, because twenty-four races of a mediocre
   rookie campaign outvoted ten dominant ones. A driver who steps up has to be
   allowed to step up.

   Within 2026, skill is held fixed. With ten in-regulation races and exactly two
   cars per team, a simultaneous random walk on skill *and* car is not identified —
   the two would trade off freely race to race. The flexibility goes where the real
   in-season signal is: the development race.

3. **Retirements are excluded from the likelihood.** A DNF is a reliability event,
   not a pace event. Keeping retired cars in the ranking denominators would let a
   gearbox failure masquerade as a slow car. Reliability is modelled separately as
   a hazard process in Layer 2, so the two stay unconflated here.

Even with these, driver and constructor effects are only *weakly* separated: within
a fixed pairing you can add a constant to both team-mates and subtract it from their
car with no change in likelihood. What breaks that degeneracy is (a) the hierarchical
priors, which shrink both sets toward zero, and (b) drivers moving between teams.
The posterior intervals on the split are correspondingly wide, and should be read
that way.
"""

from __future__ import annotations

from dataclasses import dataclass

import jax
import jax.numpy as jnp
import numpy as np
import numpyro
import numpyro.distributions as dist
import pandas as pd
from jax.scipy.special import logsumexp
from numpyro.infer import MCMC, NUTS

# 2025 Ergast/Jolpica constructor ids -> the 2026 entity that continues them. A team
# that rebrands is the same entrant with the same factory, so it keeps its identity;
# only the regulation boundary severs its *performance*, which is handled in the model.
CONSTRUCTOR_CONTINUITY = {
    "mclaren": "McLaren", "mercedes": "Mercedes", "red_bull": "Red Bull Racing",
    "ferrari": "Ferrari", "williams": "Williams", "rb": "Racing Bulls",
    "aston_martin": "Aston Martin", "haas": "Haas F1 Team", "sauber": "Audi",
    "alpine": "Alpine",
}


@dataclass
class StrengthData:
    """Padded arrays in the shape NumPyro wants, plus the index maps to read them back."""
    order_driver: np.ndarray   # (R, N) driver index of the k-th classified finisher
    order_cons: np.ndarray     # (R, N) constructor index of the k-th finisher
    valid: np.ndarray          # (R, N) bool — is slot k a real finisher
    era: np.ndarray            # (R,) 0 = 2025, 1 = 2026
    round_ix: np.ndarray       # (R,) 0-based round within 2026 (0 for 2025 races)
    grid_adv: np.ndarray       # (R, N) starting-position advantage, centred per race
    circuit_ix: np.ndarray     # (R,) index into `circuits`
    drivers: list[str]
    constructors: list[str]
    circuits: list[str]
    n_2026_rounds: int
    n_circuits: int
    races: pd.DataFrame        # one row per race, for reporting


def grid_advantage(grid: np.ndarray) -> np.ndarray:
    """Turn starting positions into a covariate, as −log(position) centred per race.

    Log, not linear: the gap between P1 and P2 is worth far more than the gap between
    P15 and P16, and a log scale encodes that without spending a parameter per slot.
    Negated so a positive coefficient reads as "starting further forward helps".
    A grid of 0 is the Ergast convention for a pit-lane start, so it is mapped behind
    the last classified slot rather than treated as pole.
    """
    g = np.asarray(grid, dtype=float).copy()
    n = np.nanmax(g) if np.isfinite(g).any() else 20.0
    g[(g <= 0) | ~np.isfinite(g)] = n + 1
    return -np.log(g)


def build(results_2025: pd.DataFrame, results_2026: pd.DataFrame,
          sprints_2026: pd.DataFrame | None = None) -> StrengthData:
    """Assemble both seasons into a single padded ranking dataset.

    Sprint races are included when supplied. They are shorter and carry no mandatory
    stop, so they are not identical events — but they are still a full field of the same
    cars ranked on pace, and there are four of them against ten grands prix. Discarding a
    40% increase in in-regulation ranking data to preserve purity is the worse trade.
    """
    rows = []

    r25 = results_2025[results_2025["classified"]].copy()
    r25["team"] = r25["constructor_id"].map(CONSTRUCTOR_CONTINUITY)
    unmapped = r25.loc[r25["team"].isna(), "constructor_id"].unique()
    if len(unmapped):
        raise ValueError(f"unmapped 2025 constructors: {list(unmapped)}")
    for (rnd, event), g in r25.groupby(["round", "event"], sort=True):
        g = g.sort_values("position")
        rows.append({"season": 2025, "round": int(rnd), "event": event,
                     "codes": g["code"].tolist(), "teams": g["team"].tolist(),
                     "grid": g["grid"].tolist()})

    r26 = results_2026.copy()
    r26 = r26[r26["ClassifiedPosition"].astype(str).str.isdigit()]
    for (rnd, event), g in r26.groupby(["round", "event"], sort=True):
        g = g.sort_values("Position")
        rows.append({"season": 2026, "round": int(rnd), "event": event,
                     "codes": g["Abbreviation"].tolist(), "teams": g["TeamName"].tolist(),
                     "grid": g["GridPosition"].tolist()})

    if sprints_2026 is not None and not sprints_2026.empty:
        sp = sprints_2026[sprints_2026["ClassifiedPosition"].astype(str).str.isdigit()]
        for (rnd, event), g in sp.groupby(["round", "event"], sort=True):
            g = g.sort_values("Position")
            rows.append({"season": 2026, "round": int(rnd), "event": f"{event} (sprint)",
                         "codes": g["Abbreviation"].tolist(),
                         "teams": g["TeamName"].tolist(),
                         "grid": g["GridPosition"].tolist()})

    races = pd.DataFrame(rows).sort_values(["season", "round"]).reset_index(drop=True)

    drivers = sorted({c for r in races["codes"] for c in r})
    constructors = sorted({t for r in races["teams"] for t in r})
    # Circuit identity comes from the event name, which is stable across seasons for the
    # venues that repeat and simply unique for the ones that do not.
    circuits = sorted(races["event"].unique())
    d_ix = {d: i for i, d in enumerate(drivers)}
    c_ix = {c: i for i, c in enumerate(constructors)}

    R = len(races)
    N = int(races["codes"].map(len).max())
    order_driver = np.zeros((R, N), dtype=np.int32)
    order_cons = np.zeros((R, N), dtype=np.int32)
    valid = np.zeros((R, N), dtype=bool)
    grid_adv = np.zeros((R, N), dtype=np.float32)

    for r, row in races.iterrows():
        k = len(row["codes"])
        order_driver[r, :k] = [d_ix[c] for c in row["codes"]]
        order_cons[r, :k] = [c_ix[t] for t in row["teams"]]
        valid[r, :k] = True
        adv = grid_advantage(np.asarray(row["grid"], dtype=float))
        grid_adv[r, :k] = adv - adv.mean()      # centred so it shifts no overall level

    era = (races["season"] == 2026).to_numpy().astype(np.int32)
    round_ix = np.where(era == 1, races["round"].to_numpy() - 1, 0).astype(np.int32)
    circuit_ix = races["event"].map({c: i for i, c in enumerate(circuits)}).to_numpy().astype(np.int32)

    return StrengthData(order_driver, order_cons, valid, era, round_ix, grid_adv,
                        circuit_ix, drivers, constructors, circuits,
                        int(round_ix[era == 1].max()) + 1, len(circuits), races)


def _plackett_luce_loglik(theta: jnp.ndarray, valid: jnp.ndarray,
                          top_m: int | None = None) -> jnp.ndarray:
    """Log-likelihood of the observed orders, optionally truncated to the top M.

    `theta` is already sorted by finishing position, so the denominator at step k is a
    reverse-cumulative logsumexp over slots k..N-1. With at most ~22 entrants the dense
    triangular form is cheaper than a scan and keeps the whole thing differentiable.

    **Truncation matters more than it looks.** The full-order likelihood treats being
    classified 15th as strong evidence of a slow car, when in practice a midfield
    classification usually means first-lap damage, a bad pit stop or a penalty — noise
    about pace, not signal. Modelling only the first M positions (and leaving the tail
    as an unordered "finished outside the top M") is the standard truncated
    Plackett-Luce, and it is what stops two incident-hit races from outvoting six wins.
    Positions beyond M still populate every denominator, so the tail is not discarded —
    it just stops being read as a precise ranking.
    """
    N = theta.shape[-1]
    neg_inf = jnp.float32(-1e30)
    theta_v = jnp.where(valid, theta, neg_inf)

    keep = jnp.triu(jnp.ones((N, N), dtype=bool))              # keep[k, j] = j >= k
    cand = jnp.where(keep[None, :, :], theta_v[:, None, :], neg_inf)
    denom = logsumexp(cand, axis=-1)                            # (R, N)

    use = valid
    if top_m is not None:
        use = use & (jnp.arange(N) < top_m)[None, :]
    terms = jnp.where(use, theta_v - denom, 0.0)
    return terms.sum()


def _attrition_loglik(theta: jnp.ndarray, valid: jnp.ndarray) -> jnp.ndarray:
    """Reverse Plackett-Luce — the 'attrition' model of Graves, Reese & Fitzgerald (2003).

    Instead of repeatedly drawing the *best* remaining car, this draws the *worst*: the
    last-placed driver is the one beaten by everyone, then the second-from-last among
    those who remain, and so on. The strongest drivers are the ones who survive longest.

    Graves et al. proposed it for NASCAR precisely because the forward Plackett-Luce is,
    in Henderson & Kirrane's summary, "strongly influenced by poor results and therefore
    penalising the good drivers too harshly for the occasional lowly finish" — finishes
    that in motor racing are "commonplace … due to reliability issues with the cars which
    are beyond the driver's control, crashes and so on". That is exactly the failure this
    project hit with Antonelli, so it is worth testing rather than assuming.

    Mechanically it is the forward model with the ordering reversed and theta negated,
    which here is a lower-triangular candidate mask instead of an upper-triangular one:
    at slot k the candidate set is slots 0..k rather than k..N-1.
    """
    N = theta.shape[-1]
    neg_inf = jnp.float32(-1e30)
    nt = jnp.where(valid, -theta, neg_inf)

    keep = jnp.tril(jnp.ones((N, N), dtype=bool))              # keep[k, j] = j <= k
    cand = jnp.where(keep[None, :, :], nt[:, None, :], neg_inf)
    denom = logsumexp(cand, axis=-1)

    return jnp.where(valid, nt - denom, 0.0).sum()


def _contaminated_loglik(theta: jnp.ndarray, valid: jnp.ndarray, eps: jnp.ndarray,
                         top_m: int | None = None) -> jnp.ndarray:
    """Plackett-Luce with a uniform contamination component.

    At each selection step the next finisher is drawn by ability with probability 1−eps,
    and uniformly at random from the cars still running with probability eps. So eps is
    the share of positions decided by something other than pace — contact, a penalty, a
    slow stop — and the model can attribute a wildly out-of-character result to chaos
    instead of revising its estimate of the car.

    This is the same idea as a contaminated-normal likelihood in robust regression, moved
    onto rankings: a heavy tail that stops one bad race dominating the fit. eps is
    estimated, not assumed, so the data decides how much chaos there is.
    """
    N = theta.shape[-1]
    neg_inf = jnp.float32(-1e30)
    theta_v = jnp.where(valid, theta, neg_inf)

    keep = jnp.triu(jnp.ones((N, N), dtype=bool))
    cand = jnp.where(keep[None, :, :], theta_v[:, None, :], neg_inf)
    denom = logsumexp(cand, axis=-1)
    ll_ability = theta_v - denom

    # Uniform over the cars still to be placed: 1/(number remaining).
    n_remaining = jnp.cumsum(valid[:, ::-1], axis=1)[:, ::-1]
    ll_uniform = -jnp.log(jnp.maximum(n_remaining, 1))

    mixed = jnp.logaddexp(jnp.log1p(-eps) + ll_ability, jnp.log(eps) + ll_uniform)

    use = valid
    if top_m is not None:
        use = use & (jnp.arange(N) < top_m)[None, :]
    return jnp.where(use, mixed, 0.0).sum()


# Model the points-paying positions as an ordering; treat everything behind them as an
# unordered tail. In F1 the top ten is the natural cut — it is where the racing is being
# decided on pace rather than on attrition. Henderson & Kirrane (2018) motivate exactly
# this cut from the points system: "Censoring the observations by pooling these lower
# placed drivers together may be better at forecasting the winner or other high placed
# finishing positions."
TOP_M = 10

# forward   — truncated Plackett-Luce (Henderson & Kirrane 2018)
# attrition — reverse Plackett-Luce (Graves et al. 2003)
# contaminated — Plackett-Luce with an estimated uniform noise component
LIKELIHOODS = ("forward", "attrition", "contaminated")


def model(d: StrengthData, top_m: int | None = TOP_M, use_grid: bool = False,
          likelihood: str = "forward"):
    """`use_grid` switches the model between two genuinely different questions.

    Without it, the answer is "how good is this driver-car combination" — an unconditional
    strength estimate, which is what the driver-versus-car analysis needs.

    With it, the answer is "given where everyone starts, who wins" — the question you
    actually have on a Sunday morning. The two are not interchangeable: qualifying is
    itself caused by skill and car, so conditioning on grid deliberately absorbs part of
    the very effect the unconditional model is trying to measure. The skill and car terms
    in the grid-conditional fit mean "race-day performance beyond what qualifying already
    revealed", which is why the project fits and reports both rather than picking one.
    """
    n_d, n_c, n_t = len(d.drivers), len(d.constructors), d.n_2026_rounds

    sigma_skill = numpyro.sample("sigma_skill", dist.HalfNormal(1.0))
    # How far a driver's level is allowed to move across the regulation break. Wide
    # enough for a genuine step up, tight enough that ten races cannot invent one.
    sigma_delta = numpyro.sample("sigma_delta", dist.HalfNormal(0.75))
    sigma_car25 = numpyro.sample("sigma_car25", dist.HalfNormal(2.0))
    sigma_car26 = numpyro.sample("sigma_car26", dist.HalfNormal(2.0))
    # In-season development. Kept tight: a team does not remake its car every fortnight.
    sigma_walk = numpyro.sample("sigma_walk", dist.HalfNormal(0.25))

    # Non-centred parameterisation throughout — the funnel geometry is severe otherwise.
    skill_raw = numpyro.sample("skill_raw", dist.Normal(0, 1).expand([n_d]).to_event(1))
    delta_raw = numpyro.sample("delta_raw", dist.Normal(0, 1).expand([n_d]).to_event(1))
    car25_raw = numpyro.sample("car25_raw", dist.Normal(0, 1).expand([n_c]).to_event(1))
    car26_raw = numpyro.sample("car26_raw", dist.Normal(0, 1).expand([n_c]).to_event(1))
    walk_raw = numpyro.sample("walk_raw",
                              dist.Normal(0, 1).expand([n_c, n_t - 1]).to_event(2))

    # Centring is what makes the additive split identified at all: without it the whole
    # driver vector and the whole constructor vector can slide against each other. Each
    # era is centred separately, so skill is read relative to that season's field.
    skill_base = skill_raw * sigma_skill
    skill25 = numpyro.deterministic("skill25", skill_base - skill_base.mean())
    skill_2026 = skill_base + delta_raw * sigma_delta
    skill = numpyro.deterministic("skill", skill_2026 - skill_2026.mean())
    numpyro.deterministic("skill_delta", skill - skill25)

    car25 = car25_raw * sigma_car25
    car25 = numpyro.deterministic("car25", car25 - car25.mean())

    car26_0 = car26_raw * sigma_car26
    steps = walk_raw * sigma_walk
    car26 = jnp.concatenate([car26_0[:, None], car26_0[:, None] + jnp.cumsum(steps, axis=1)],
                            axis=1)                              # (n_c, n_t)
    car26 = numpyro.deterministic("car26", car26 - car26.mean(axis=0, keepdims=True))

    is26 = d.era[:, None] == 1
    theta_skill = jnp.where(is26, skill[d.order_driver], skill25[d.order_driver])
    theta_car = jnp.where(is26,
                          car26[d.order_cons, d.round_ix[:, None]],
                          car25[d.order_cons])
    theta = theta_skill + theta_car

    if use_grid:
        # Positive beta = starting further forward helps. Half-normal keeps the sign
        # fixed: a negative track advantage would be a fitting artefact, not physics.
        #
        # One global beta says the Hungaroring and Monza are the same race, which is the
        # single least defensible thing a grid term can assume. Each circuit gets its own
        # multiplier, partially pooled toward the championship mean so a circuit seen once
        # or twice cannot run away with an extreme value.
        beta_grid = numpyro.sample("beta_grid", dist.HalfNormal(2.0))
        sigma_circuit = numpyro.sample("sigma_circuit", dist.HalfNormal(0.35))
        circ_raw = numpyro.sample("circuit_raw",
                                  dist.Normal(0, 1).expand([d.n_circuits]).to_event(1))
        # exp() keeps every circuit multiplier positive: track position can matter more
        # or less, but starting further forward never becomes a disadvantage.
        circ_mult = numpyro.deterministic("circuit_mult",
                                          jnp.exp(circ_raw * sigma_circuit))
        beta_c = beta_grid * circ_mult[d.circuit_ix][:, None]
        theta = theta + beta_c * jnp.asarray(d.grid_adv)

    valid = jnp.asarray(d.valid)
    if likelihood == "attrition":
        # The reverse model reads the whole order robustly, so it is not truncated:
        # truncation and attrition are alternative answers to the same problem.
        ll = _attrition_loglik(theta, valid)
    elif likelihood == "contaminated":
        eps = numpyro.sample("eps", dist.Beta(2.0, 20.0))
        ll = _contaminated_loglik(theta, valid, eps, top_m)
    else:
        ll = _plackett_luce_loglik(theta, valid, top_m)
    numpyro.factor("rank_likelihood", ll)


def fit(d: StrengthData, warmup: int = 1000, samples: int = 1000, chains: int = 4,
        seed: int = 20260725, use_grid: bool = False,
        likelihood: str = "forward") -> MCMC:
    if likelihood not in LIKELIHOODS:
        raise ValueError(f"likelihood must be one of {LIKELIHOODS}, got {likelihood!r}")
    numpyro.set_host_device_count(chains)
    kernel = NUTS(model, target_accept_prob=0.9)
    mcmc = MCMC(kernel, num_warmup=warmup, num_samples=samples, num_chains=chains,
                progress_bar=False)
    mcmc.run(jax.random.PRNGKey(seed), d, TOP_M, use_grid, likelihood)
    return mcmc


def predict_order(post: dict, d: StrengthData, entries: list[tuple[str, str]],
                  steps_ahead: int = 1, n_sim: int = 400, seed: int = 7,
                  grid: list[float] | None = None,
                  likelihood: str = "forward",
                  circuit: str | None = None) -> tuple[np.ndarray, np.ndarray]:
    """Finishing-order probabilities for an upcoming race.

    Each posterior draw is pushed `steps_ahead` rounds forward along the constructor
    random walk (so forecast uncertainty grows with distance, as it should), then the
    Plackett-Luce order is sampled exactly via the Gumbel-max trick: adding standard
    Gumbel noise to each theta and sorting yields a draw from the PL distribution.

    Returns (position_probs (n_entries, n_entries), theta_draws (n_draws, n_entries)).
    """
    rng = np.random.default_rng(seed)
    d_ix = {x: i for i, x in enumerate(d.drivers)}
    c_ix = {x: i for i, x in enumerate(d.constructors)}

    skill = np.asarray(post["skill"])                    # (S, n_d)
    car26 = np.asarray(post["car26"])                    # (S, n_c, n_t)
    sigma_walk = np.asarray(post["sigma_walk"])          # (S,)
    S = skill.shape[0]

    last = car26[:, :, -1]
    drift = rng.normal(0.0, 1.0, size=(S, car26.shape[1])) * sigma_walk[:, None] * np.sqrt(steps_ahead)
    car_next = last + drift

    n = len(entries)
    theta = np.zeros((S, n))
    for j, (code, team) in enumerate(entries):
        s = skill[:, d_ix[code]] if code in d_ix else rng.normal(0, np.asarray(post["sigma_skill"]))
        c = car_next[:, c_ix[team]] if team in c_ix else np.zeros(S)
        theta[:, j] = s + c

    if grid is not None and "beta_grid" in post:
        adv = grid_advantage(np.asarray(grid, dtype=float))
        beta = np.asarray(post["beta_grid"])
        # Use this circuit's own multiplier when we have seen it before. Overtaking
        # difficulty is a property of the track, and a championship-wide average
        # understates pole somewhere like the Hungaroring and overstates it at Monza.
        if circuit is not None and "circuit_mult" in post and circuit in d.circuits:
            beta = beta * np.asarray(post["circuit_mult"])[:, d.circuits.index(circuit)]
        theta = theta + beta[:, None] * (adv - adv.mean())[None, :]

    counts = np.zeros((n, n))
    for _ in range(n_sim):
        g = rng.gumbel(size=(S, n))
        if likelihood == "attrition":
            # The reverse model generates worst-first with weights exp(-theta), so the
            # Gumbel draw is applied to -theta and the resulting order flipped. Gumbel is
            # asymmetric, so this is genuinely not the same as sampling the forward model.
            worst_first = np.argsort(-(-theta + g), axis=1)
            order = worst_first[:, ::-1]
        else:
            order = np.argsort(-(theta + g), axis=1)
        for pos in range(n):
            np.add.at(counts, (order[:, pos], pos), 1)
    probs = counts / counts.sum(axis=1, keepdims=True)
    return probs, theta
